qubes: change symlink to be relative, and move to bin
Otherwise some meson versions complains:

    Installing /build/fwupd-qubes-1.8.14/contrib/qubes/src/qubes_fwupdmgr.py to /build/fwupd-qubes-1.8.14/debian/tmp/usr/share/qubes-fwupd/src
    ...
    ERROR: Tried to install symlink to missing file /usr/share/qubes-fwupd/src/qubes_fwupdmgr.py

Additionally move it to /usr/bin, to match fwupdmgr location in Fedora.